### ISSUE TITLE
This lib is buggy

### ISSUE THREAD

**Issue by RomanHotsiy** [jspm/nodelibs-https#1]
Seems you've copied this lib from [substack/https-browserify](https://github.com/substack/https-browserify)
But this module is buggy, check the issue: https://github.com/substack/https-browserify/issues/6.
It is closed but the issue is not fixed.

**Comment by 0815fox** [comment]
I can confirm that.

**Comment by guybedford** [comment]
I believe this is fixed by the use of `stream-http` in jspm 0.17.
